### ISSUE TITLE
无法启动

### ISSUE THREAD

**Issue by wmbin** [moonstack/moon-kibana#2]
启动异常信息如下：
module.js:340
    throw err;
          ^
Error: Cannot find module 'commander'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/hadoop/elk/moon-kibana/src/bin/kibana.js:3:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)

安装commander

module.js:340
    throw err;
          ^
Error: Cannot find module 'npmlog'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at /usr/local/moon-kibana/node/bin/npm:19:11
    at Object.<anonymous> (/usr/local/moon-kibana/node/bin/npm:87:3)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)

自行安装node也是一样的

**Comment by wenph** [comment]
怎么安装commander啊？网上有Midnight Commander、Double Commander、Total Commander、System Commander、 GNOME Commander，到底是哪个啊？

**Comment by longbinma** [comment]
[root@iZ23gp85q5qZ opt]# ./kibana/bin/kibana                 
module.js:327
    throw err;
    ^

Error: Cannot find module 'commander'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/opt/kibana/src/bin/kibana.js:3:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)

[root@iZ23gp85q5qZ opt]# npm install commander     
npm http GET https://registry.npmjs.org/commander
npm http 200 https://registry.npmjs.org/commander
npm http GET https://registry.npmjs.org/commander/-/commander-2.9.0.tgz
npm http 200 https://registry.npmjs.org/commander/-/commander-2.9.0.tgz
npm http GET https://registry.npmjs.org/graceful-readlink
npm http 200 https://registry.npmjs.org/graceful-readlink
npm http GET https://registry.npmjs.org/graceful-readlink/-/graceful-readlink-1.0.1.tgz
npm http 200 https://registry.npmjs.org/graceful-readlink/-/graceful-readlink-1.0.1.tgz
commander@2.9.0 node_modules/commander
└── graceful-readlink@1.0.1

[root@iZ23gp85q5qZ opt]# ./kibana/bin/kibana       
module.js:327
    throw err;
    ^

Error: Cannot find module 'lodash'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/opt/kibana/src/config/index.js:1:71)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
[root@iZ23gp85q5qZ opt]# npm install lodash
npm http GET https://registry.npmjs.org/lodash
npm http 200 https://registry.npmjs.org/lodash
npm http GET https://registry.npmjs.org/lodash/-/lodash-4.16.1.tgz
npm http 200 https://registry.npmjs.org/lodash/-/lodash-4.16.1.tgz
lodash@4.16.1 node_modules/lodash
[root@iZ23gp85q5qZ opt]# 
[root@iZ23gp85q5qZ opt]# 
[root@iZ23gp85q5qZ opt]# ./kibana/bin/kibana
module.js:327
    throw err;
    ^

Error: Cannot find module 'js-yaml'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/opt/kibana/src/config/index.js:3:12)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
[root@iZ23gp85q5qZ opt]# npm install js-yaml
npm http GET https://registry.npmjs.org/js-yaml
npm http 200 https://registry.npmjs.org/js-yaml
npm http GET https://registry.npmjs.org/js-yaml/-/js-yaml-3.6.1.tgz
npm http 200 https://registry.npmjs.org/js-yaml/-/js-yaml-3.6.1.tgz
npm http GET https://registry.npmjs.org/argparse
npm http GET https://registry.npmjs.org/esprima
npm http 200 https://registry.npmjs.org/argparse
npm http GET https://registry.npmjs.org/argparse/-/argparse-1.0.7.tgz
npm http 200 https://registry.npmjs.org/esprima
npm http GET https://registry.npmjs.org/esprima/-/esprima-2.7.3.tgz
npm http 200 https://registry.npmjs.org/argparse/-/argparse-1.0.7.tgz
npm http 200 https://registry.npmjs.org/esprima/-/esprima-2.7.3.tgz
npm http GET https://registry.npmjs.org/sprintf-js
npm http 200 https://registry.npmjs.org/sprintf-js
npm http GET https://registry.npmjs.org/sprintf-js/-/sprintf-js-1.0.3.tgz
npm http 200 https://registry.npmjs.org/sprintf-js/-/sprintf-js-1.0.3.tgz
js-yaml@3.6.1 node_modules/js-yaml
├── esprima@2.7.3
└── argparse@1.0.7 (sprintf-js@1.0.3)
[root@iZ23gp85q5qZ opt]# ./kibana/bin/kibana
module.js:327
    throw err;
    ^

Error: Cannot find module 'glob'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/opt/kibana/src/lib/listPlugins.js:2:12)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)


接下来就无穷无尽的模块安装，这就是个天坑啊
